/**
 * Generates SQL to import bank account data + join dates from the CSV export.
 * 
 * Usage:
 *   npx tsx scripts/import-csv-bank-joindate.ts > scripts/import-data.sql
 *   Then run:
 *   npx wrangler d1 execute verein-connect-db --remote --file=scripts/import-data.sql
 */

import { readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const csvPath = join(__dirname, '../../Mitglieder_Export - Tabellenblatt1 (1).csv');
const csvContent = readFileSync(csvPath, 'utf-8');

function parseCSVLine(line: string): string[] {
  const fields: string[] = [];
  let current = '';
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (inQuotes) {
      if (ch === '"' && line[i + 1] === '"') {
        current += '"';
        i++;
      } else if (ch === '"') {
        inQuotes = false;
      } else {
        current += ch;
      }
    } else {
      if (ch === '"') {
        inQuotes = true;
      } else if (ch === ',') {
        fields.push(current.trim());
        current = '';
      } else {
        current += ch;
      }
    }
  }
  fields.push(current.trim());
  return fields;
}

function parseDate(raw: string): string | null {
  if (!raw) return null;
  raw = raw.trim();
  
  // Handle obviously bad dates like "27/3/4917"
  const parts = raw.split('/');
  if (parts.length !== 3) return null;
  
  let day = parseInt(parts[0], 10);
  let month = parseInt(parts[1], 10);
  let year = parseInt(parts[2], 10);
  
  if (isNaN(day) || isNaN(month) || isNaN(year)) return null;
  
  // Handle 2-digit years
  if (year < 100) {
    year = year >= 50 ? 1900 + year : 2000 + year;
  }
  
  // Sanity check
  if (year > 2030 || year < 1950) return null;
  if (month < 1 || month > 12) return null;
  if (day < 1 || day > 31) return null;
  
  return `${year}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
}

function esc(s: string): string {
  return s.replace(/'/g, "''");
}

const lines = csvContent.split('\n').filter(l => l.trim());
// Skip header
const dataLines = lines.slice(1);

// Parse all rows first
interface RowData {
  rowNum: number;
  lastName: string;
  firstName: string;
  email: string;
  ktoInhaber: string;
  iban: string;
  bic: string;
  bank: string;
  sepaDateRaw: string;
  eintrittRaw: string;
}

const allRows: RowData[] = [];
for (let i = 0; i < dataLines.length; i++) {
  const fields = parseCSVLine(dataLines[i]);
  allRows.push({
    rowNum: i + 2,
    lastName: (fields[1] || '').trim(),
    firstName: (fields[2] || '').trim(),
    email: (fields[7] || '').trim().toLowerCase(),
    ktoInhaber: (fields[13] || '').trim(),
    iban: (fields[14] || '').trim(),
    bic: (fields[15] || '').trim(),
    bank: (fields[16] || '').trim(),
    sepaDateRaw: (fields[17] || '').trim(),
    eintrittRaw: (fields[18] || '').trim(),
  });
}

// Rows 138-171 (0-indexed: 137-170) have SHIFTED bank data:
// The KTO Inhaber/IBAN/BIC/Bank/SEPA on row N belongs to the member on row N-1.
// We detect this by checking if KTO Inhaber matches the PREVIOUS row's name.
// Shifted range: CSV rows 139-171 (dataLines index 137-169)
const SHIFTED_START = 137; // dataLines index for CSV row 139
const SHIFTED_END = 169;   // dataLines index for CSV row 171

// Build a map: for shifted rows, collect bank data keyed by the person it belongs to
// For shifted rows, the bank data on row i belongs to the member on row i-1
interface BankInfo {
  ktoInhaber: string;
  iban: string;
  bic: string;
  bank: string;
  sepaDateRaw: string;
}

// Collect bank data from shifted rows and assign to previous row's member
const shiftedBankData = new Map<number, BankInfo>(); // key = dataLines index of the OWNER
for (let i = SHIFTED_START; i <= SHIFTED_END && i < allRows.length; i++) {
  const row = allRows[i];
  if (row.iban.length > 10 && row.ktoInhaber.length > 0) {
    // This bank data belongs to the member on the previous row (i-1)
    shiftedBankData.set(i - 1, {
      ktoInhaber: row.ktoInhaber,
      iban: row.iban,
      bic: row.bic,
      bank: row.bank,
      sepaDateRaw: row.sepaDateRaw,
    });
  }
}

const sqlStatements: string[] = [];

sqlStatements.push('-- Import bank accounts + join dates from CSV export');
sqlStatements.push('-- Generated by import-csv-bank-joindate.ts');
sqlStatements.push('-- Matches members by LOWER(email) + LOWER(last_name) + LOWER(first_name)');
sqlStatements.push('');

function emitBankInsert(email: string, lastName: string, firstName: string, bankInfo: BankInfo) {
  const sepaDate = parseDate(bankInfo.sepaDateRaw);
  const id = crypto.randomUUID();
  sqlStatements.push(
    `INSERT INTO bank_accounts (id, org_id, user_id, account_holder, iban, bic, bank_name, sepa_mandate, sepa_mandate_date) ` +
    `SELECT '${id}', u.org_id, u.id, '${esc(bankInfo.ktoInhaber)}', '${esc(bankInfo.iban)}', ${bankInfo.bic ? `'${esc(bankInfo.bic)}'` : 'NULL'}, ${bankInfo.bank ? `'${esc(bankInfo.bank)}'` : 'NULL'}, ${sepaDate ? 1 : 0}, ${sepaDate ? `'${sepaDate}'` : 'NULL'} ` +
    `FROM users u ` +
    `WHERE LOWER(u.email) = '${esc(email)}' ` +
    `AND LOWER(u.last_name) = '${esc(lastName.toLowerCase())}' ` +
    `AND LOWER(u.first_name) = '${esc(firstName.toLowerCase())}' ` +
    `AND NOT EXISTS (SELECT 1 FROM bank_accounts ba WHERE ba.user_id = u.id) ` +
    `LIMIT 1;`
  );
}

for (let i = 0; i < allRows.length; i++) {
  const row = allRows[i];
  const { lastName, firstName, email } = row;
  
  // Skip rows without email or name
  if (!email || !lastName || !firstName) continue;
  // Skip emails with spaces/slashes (invalid)
  if (email.includes(' ')) continue;
  
  const isInShiftedRange = i >= SHIFTED_START && i <= SHIFTED_END;
  
  // Join date: always from current row's Eintritt column (not shifted)
  const joinDate = parseDate(row.eintrittRaw);
  
  // Bank data: for shifted rows, use the shifted lookup; for normal rows, use inline data
  let bankInfo: BankInfo | null = null;
  if (isInShiftedRange) {
    // Bank data for this member comes from shiftedBankData map
    const shifted = shiftedBankData.get(i);
    if (shifted) bankInfo = shifted;
  } else {
    // Normal rows: bank data is inline
    if (row.iban.length > 10 && row.ktoInhaber.length > 0) {
      bankInfo = {
        ktoInhaber: row.ktoInhaber,
        iban: row.iban,
        bic: row.bic,
        bank: row.bank,
        sepaDateRaw: row.sepaDateRaw,
      };
    }
  }
  
  if (!joinDate && !bankInfo) continue;
  
  sqlStatements.push(`-- Row ${row.rowNum}: ${firstName} ${lastName} (${email})`);
  
  if (joinDate) {
    sqlStatements.push(
      `UPDATE users SET join_date = '${joinDate}' ` +
      `WHERE LOWER(email) = '${esc(email)}' ` +
      `AND LOWER(last_name) = '${esc(lastName.toLowerCase())}' ` +
      `AND LOWER(first_name) = '${esc(firstName.toLowerCase())}';`
    );
  }
  
  if (bankInfo) {
    emitBankInsert(email, lastName, firstName, bankInfo);
  }
  
  sqlStatements.push('');
}

console.log(sqlStatements.join('\n'));
